### ISSUE TITLE
卷轴浏览BUG 【1.6.3版本】

### ISSUE THREAD

**Issue by yuxic9894** [SchneeHertz/exhentai-manga-manager#182]
双页和单页浏览正常的漫画，卷轴浏览图片会有吞掉前面的页面，也有页面顺序不对的情况

**Comment by SchneeHertz** [comment]
在自定义css中增加
```css
.drawer-viewer-body { display: initial !important; }
```
临时修复这个问题
下个版本修复
